ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-"{{ env }}".devopsgeek.online
CATALOGUE_HOST: catalogue-"{{ env }}".devopsgeek.online
REDIS_HOST: redis-"{{ env }}".devopsgeek.online
USER_HOST: user-"{{ env }}".devopsgeek.online
CART_HOST: cart-"{{ env }}".devopsgeek.online
MYSQL_HOST: mysql-"{{ env }}".devopsgeek.online
SHIPPING_HOST: shipping-"{{ env }}".devopsgeek.online
RABBITMQ_HOST: rabbitmq-"{{ env }}".devopsgeek.online
PAYMENT_HOST: payment-"{{ env }}".devopsgeek.online